// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matmul_1_matmul_1,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu11p-flga2577-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.297000,HLS_SYN_LAT=65,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1935,HLS_SYN_LUT=1768,HLS_VERSION=2023_2}" *)

module matmul_1 (
        ap_clk,
        ap_rst_n,
        in_A_TDATA,
        in_A_TVALID,
        in_A_TREADY,
        in_A_TKEEP,
        in_A_TSTRB,
        in_A_TLAST,
        out_C_TDATA,
        out_C_TVALID,
        out_C_TREADY,
        out_C_TKEEP,
        out_C_TSTRB,
        out_C_TLAST
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_state10 = 11'd512;
parameter    ap_ST_fsm_state11 = 11'd1024;

input   ap_clk;
input   ap_rst_n;
input  [31:0] in_A_TDATA;
input   in_A_TVALID;
output   in_A_TREADY;
input  [3:0] in_A_TKEEP;
input  [3:0] in_A_TSTRB;
input  [0:0] in_A_TLAST;
output  [31:0] out_C_TDATA;
output   out_C_TVALID;
input   out_C_TREADY;
output  [3:0] out_C_TKEEP;
output  [3:0] out_C_TSTRB;
output  [0:0] out_C_TLAST;

 reg    ap_rst_n_inv;
reg   [3:0] output_C_address0;
reg    output_C_ce0;
reg    output_C_we0;
wire   [31:0] output_C_q0;
wire    grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_ap_start;
wire    grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_ap_done;
wire    grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_ap_idle;
wire    grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_ap_ready;
wire    grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_in_A_TREADY;
wire   [31:0] grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out;
wire    grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out_ap_vld;
wire   [31:0] grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out1;
wire    grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out1_ap_vld;
wire   [31:0] grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out2;
wire    grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out2_ap_vld;
wire   [31:0] grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out3;
wire    grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out3_ap_vld;
wire   [31:0] grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out4;
wire    grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out4_ap_vld;
wire   [31:0] grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out5;
wire    grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out5_ap_vld;
wire   [31:0] grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out6;
wire    grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out6_ap_vld;
wire   [31:0] grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out7;
wire    grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out7_ap_vld;
wire   [31:0] grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out8;
wire    grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out8_ap_vld;
wire    grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_ap_start;
wire    grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_ap_done;
wire    grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_ap_idle;
wire    grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_ap_ready;
wire    grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_in_A_TREADY;
wire   [31:0] grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out;
wire    grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out_ap_vld;
wire   [31:0] grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out1;
wire    grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out1_ap_vld;
wire   [31:0] grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out2;
wire    grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out2_ap_vld;
wire   [31:0] grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out3;
wire    grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out3_ap_vld;
wire   [31:0] grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out4;
wire    grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out4_ap_vld;
wire   [31:0] grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out5;
wire    grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out5_ap_vld;
wire   [31:0] grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out6;
wire    grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out6_ap_vld;
wire   [31:0] grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out7;
wire    grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out7_ap_vld;
wire   [31:0] grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out8;
wire    grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out8_ap_vld;
wire   [3:0] grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_phi_out;
wire    grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_phi_out_ap_vld;
wire   [3:0] grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_phi7_out;
wire    grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_phi7_out_ap_vld;
wire    grp_matmul_1_Pipeline_loop1_loop2_fu_186_ap_start;
wire    grp_matmul_1_Pipeline_loop1_loop2_fu_186_ap_done;
wire    grp_matmul_1_Pipeline_loop1_loop2_fu_186_ap_idle;
wire    grp_matmul_1_Pipeline_loop1_loop2_fu_186_ap_ready;
wire   [3:0] grp_matmul_1_Pipeline_loop1_loop2_fu_186_output_C_address0;
wire    grp_matmul_1_Pipeline_loop1_loop2_fu_186_output_C_ce0;
wire    grp_matmul_1_Pipeline_loop1_loop2_fu_186_output_C_we0;
wire   [31:0] grp_matmul_1_Pipeline_loop1_loop2_fu_186_output_C_d0;
wire    grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_ap_start;
wire    grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_ap_done;
wire    grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_ap_idle;
wire    grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_ap_ready;
wire    grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TREADY;
wire   [3:0] grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_output_C_address0;
wire    grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_output_C_ce0;
wire   [31:0] grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TDATA;
wire    grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TVALID;
wire   [3:0] grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TKEEP;
wire   [3:0] grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TSTRB;
wire   [0:0] grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TLAST;
reg    grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_ap_start_reg;
(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg    grp_matmul_1_Pipeline_loop1_loop2_fu_186_ap_start_reg;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
reg    grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_ap_start_reg;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
reg   [10:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    regslice_both_out_C_V_data_V_U_apdone_blk;
wire    ap_CS_fsm_state11;
wire    regslice_both_in_A_V_data_V_U_apdone_blk;
wire   [31:0] in_A_TDATA_int_regslice;
wire    in_A_TVALID_int_regslice;
reg    in_A_TREADY_int_regslice;
wire    regslice_both_in_A_V_data_V_U_ack_in;
wire    regslice_both_in_A_V_keep_V_U_apdone_blk;
wire   [3:0] in_A_TKEEP_int_regslice;
wire    regslice_both_in_A_V_keep_V_U_vld_out;
wire    regslice_both_in_A_V_keep_V_U_ack_in;
wire    regslice_both_in_A_V_strb_V_U_apdone_blk;
wire   [3:0] in_A_TSTRB_int_regslice;
wire    regslice_both_in_A_V_strb_V_U_vld_out;
wire    regslice_both_in_A_V_strb_V_U_ack_in;
wire    regslice_both_in_A_V_last_V_U_apdone_blk;
wire   [0:0] in_A_TLAST_int_regslice;
wire    regslice_both_in_A_V_last_V_U_vld_out;
wire    regslice_both_in_A_V_last_V_U_ack_in;
wire    out_C_TVALID_int_regslice;
wire    out_C_TREADY_int_regslice;
wire    regslice_both_out_C_V_data_V_U_vld_out;
wire    regslice_both_out_C_V_keep_V_U_apdone_blk;
wire    regslice_both_out_C_V_keep_V_U_ack_in_dummy;
wire    regslice_both_out_C_V_keep_V_U_vld_out;
wire    regslice_both_out_C_V_strb_V_U_apdone_blk;
wire    regslice_both_out_C_V_strb_V_U_ack_in_dummy;
wire    regslice_both_out_C_V_strb_V_U_vld_out;
wire    regslice_both_out_C_V_last_V_U_apdone_blk;
wire    regslice_both_out_C_V_last_V_U_ack_in_dummy;
wire    regslice_both_out_C_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_ap_start_reg = 1'b0;
#0 ap_CS_fsm = 11'd1;
#0 grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_ap_start_reg = 1'b0;
#0 grp_matmul_1_Pipeline_loop1_loop2_fu_186_ap_start_reg = 1'b0;
#0 grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_ap_start_reg = 1'b0;
end

matmul_1_output_C_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 9 ),
    .AddressWidth( 4 ))
output_C_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(output_C_address0),
    .ce0(output_C_ce0),
    .we0(output_C_we0),
    .d0(grp_matmul_1_Pipeline_loop1_loop2_fu_186_output_C_d0),
    .q0(output_C_q0)
);

matmul_1_matmul_1_Pipeline_loop_input_A1_loop_input_A2 grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_ap_start),
    .ap_done(grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_ap_done),
    .ap_idle(grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_ap_idle),
    .ap_ready(grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_ap_ready),
    .in_A_TVALID(in_A_TVALID_int_regslice),
    .in_A_TDATA(in_A_TDATA_int_regslice),
    .in_A_TREADY(grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_in_A_TREADY),
    .in_A_TKEEP(in_A_TKEEP_int_regslice),
    .in_A_TSTRB(in_A_TSTRB_int_regslice),
    .in_A_TLAST(in_A_TLAST_int_regslice),
    .p_out(grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out),
    .p_out_ap_vld(grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out_ap_vld),
    .p_out1(grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out1),
    .p_out1_ap_vld(grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out1_ap_vld),
    .p_out2(grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out2),
    .p_out2_ap_vld(grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out2_ap_vld),
    .p_out3(grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out3),
    .p_out3_ap_vld(grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out3_ap_vld),
    .p_out4(grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out4),
    .p_out4_ap_vld(grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out4_ap_vld),
    .p_out5(grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out5),
    .p_out5_ap_vld(grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out5_ap_vld),
    .p_out6(grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out6),
    .p_out6_ap_vld(grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out6_ap_vld),
    .p_out7(grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out7),
    .p_out7_ap_vld(grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out7_ap_vld),
    .p_out8(grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out8),
    .p_out8_ap_vld(grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out8_ap_vld)
);

matmul_1_matmul_1_Pipeline_loop_input_B1_loop_input_B2 grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_ap_start),
    .ap_done(grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_ap_done),
    .ap_idle(grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_ap_idle),
    .ap_ready(grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_ap_ready),
    .in_A_TVALID(in_A_TVALID_int_regslice),
    .in_A_TDATA(in_A_TDATA_int_regslice),
    .in_A_TREADY(grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_in_A_TREADY),
    .in_A_TKEEP(in_A_TKEEP_int_regslice),
    .in_A_TSTRB(in_A_TSTRB_int_regslice),
    .in_A_TLAST(in_A_TLAST_int_regslice),
    .p_out(grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out),
    .p_out_ap_vld(grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out_ap_vld),
    .p_out1(grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out1),
    .p_out1_ap_vld(grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out1_ap_vld),
    .p_out2(grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out2),
    .p_out2_ap_vld(grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out2_ap_vld),
    .p_out3(grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out3),
    .p_out3_ap_vld(grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out3_ap_vld),
    .p_out4(grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out4),
    .p_out4_ap_vld(grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out4_ap_vld),
    .p_out5(grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out5),
    .p_out5_ap_vld(grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out5_ap_vld),
    .p_out6(grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out6),
    .p_out6_ap_vld(grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out6_ap_vld),
    .p_out7(grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out7),
    .p_out7_ap_vld(grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out7_ap_vld),
    .p_out8(grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out8),
    .p_out8_ap_vld(grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out8_ap_vld),
    .p_phi_out(grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_phi_out),
    .p_phi_out_ap_vld(grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_phi_out_ap_vld),
    .p_phi7_out(grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_phi7_out),
    .p_phi7_out_ap_vld(grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_phi7_out_ap_vld)
);

matmul_1_matmul_1_Pipeline_loop1_loop2 grp_matmul_1_Pipeline_loop1_loop2_fu_186(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_matmul_1_Pipeline_loop1_loop2_fu_186_ap_start),
    .ap_done(grp_matmul_1_Pipeline_loop1_loop2_fu_186_ap_done),
    .ap_idle(grp_matmul_1_Pipeline_loop1_loop2_fu_186_ap_idle),
    .ap_ready(grp_matmul_1_Pipeline_loop1_loop2_fu_186_ap_ready),
    .p_reload99(grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out8),
    .p_reload98(grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out7),
    .p_reload97(grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out6),
    .p_reload96(grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out5),
    .p_reload95(grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out4),
    .p_reload94(grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out3),
    .p_reload93(grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out2),
    .p_reload92(grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out1),
    .p_reload(grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out),
    .output_C_address0(grp_matmul_1_Pipeline_loop1_loop2_fu_186_output_C_address0),
    .output_C_ce0(grp_matmul_1_Pipeline_loop1_loop2_fu_186_output_C_ce0),
    .output_C_we0(grp_matmul_1_Pipeline_loop1_loop2_fu_186_output_C_we0),
    .output_C_d0(grp_matmul_1_Pipeline_loop1_loop2_fu_186_output_C_d0),
    .p_reload118(grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out8),
    .p_reload117(grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out7),
    .p_reload116(grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out6),
    .p_reload115(grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out5),
    .p_reload114(grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out4),
    .p_reload113(grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out3),
    .p_reload112(grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out2),
    .p_reload111(grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out1),
    .p_reload110(grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out)
);

matmul_1_matmul_1_Pipeline_loop_output_C1_loop_output_C2 grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_ap_start),
    .ap_done(grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_ap_done),
    .ap_idle(grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_ap_idle),
    .ap_ready(grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_ap_ready),
    .out_C_TREADY(grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TREADY),
    .output_C_address0(grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_output_C_address0),
    .output_C_ce0(grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_output_C_ce0),
    .output_C_q0(output_C_q0),
    .p_phi_reload(grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_phi_out),
    .p_phi7_reload(grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_phi7_out),
    .out_C_TDATA(grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TDATA),
    .out_C_TVALID(grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TVALID),
    .out_C_TKEEP(grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TKEEP),
    .out_C_TSTRB(grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TSTRB),
    .out_C_TLAST(grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TLAST)
);

matmul_1_regslice_both #(
    .DataWidth( 32 ))
regslice_both_in_A_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_A_TDATA),
    .vld_in(in_A_TVALID),
    .ack_in(regslice_both_in_A_V_data_V_U_ack_in),
    .data_out(in_A_TDATA_int_regslice),
    .vld_out(in_A_TVALID_int_regslice),
    .ack_out(in_A_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_A_V_data_V_U_apdone_blk)
);

matmul_1_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_A_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_A_TKEEP),
    .vld_in(in_A_TVALID),
    .ack_in(regslice_both_in_A_V_keep_V_U_ack_in),
    .data_out(in_A_TKEEP_int_regslice),
    .vld_out(regslice_both_in_A_V_keep_V_U_vld_out),
    .ack_out(in_A_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_A_V_keep_V_U_apdone_blk)
);

matmul_1_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_A_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_A_TSTRB),
    .vld_in(in_A_TVALID),
    .ack_in(regslice_both_in_A_V_strb_V_U_ack_in),
    .data_out(in_A_TSTRB_int_regslice),
    .vld_out(regslice_both_in_A_V_strb_V_U_vld_out),
    .ack_out(in_A_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_A_V_strb_V_U_apdone_blk)
);

matmul_1_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_A_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_A_TLAST),
    .vld_in(in_A_TVALID),
    .ack_in(regslice_both_in_A_V_last_V_U_ack_in),
    .data_out(in_A_TLAST_int_regslice),
    .vld_out(regslice_both_in_A_V_last_V_U_vld_out),
    .ack_out(in_A_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_A_V_last_V_U_apdone_blk)
);

matmul_1_regslice_both #(
    .DataWidth( 32 ))
regslice_both_out_C_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TDATA),
    .vld_in(grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TVALID),
    .ack_in(out_C_TREADY_int_regslice),
    .data_out(out_C_TDATA),
    .vld_out(regslice_both_out_C_V_data_V_U_vld_out),
    .ack_out(out_C_TREADY),
    .apdone_blk(regslice_both_out_C_V_data_V_U_apdone_blk)
);

matmul_1_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_C_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TKEEP),
    .vld_in(grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TVALID),
    .ack_in(regslice_both_out_C_V_keep_V_U_ack_in_dummy),
    .data_out(out_C_TKEEP),
    .vld_out(regslice_both_out_C_V_keep_V_U_vld_out),
    .ack_out(out_C_TREADY),
    .apdone_blk(regslice_both_out_C_V_keep_V_U_apdone_blk)
);

matmul_1_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_C_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TSTRB),
    .vld_in(grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TVALID),
    .ack_in(regslice_both_out_C_V_strb_V_U_ack_in_dummy),
    .data_out(out_C_TSTRB),
    .vld_out(regslice_both_out_C_V_strb_V_U_vld_out),
    .ack_out(out_C_TREADY),
    .apdone_blk(regslice_both_out_C_V_strb_V_U_apdone_blk)
);

matmul_1_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_C_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TLAST),
    .vld_in(grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TVALID),
    .ack_in(regslice_both_out_C_V_last_V_U_ack_in_dummy),
    .data_out(out_C_TLAST),
    .vld_out(regslice_both_out_C_V_last_V_U_vld_out),
    .ack_out(out_C_TREADY),
    .apdone_blk(regslice_both_out_C_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_matmul_1_Pipeline_loop1_loop2_fu_186_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_matmul_1_Pipeline_loop1_loop2_fu_186_ap_start_reg <= 1'b1;
        end else if ((grp_matmul_1_Pipeline_loop1_loop2_fu_186_ap_ready == 1'b1)) begin
            grp_matmul_1_Pipeline_loop1_loop2_fu_186_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_ap_start_reg <= 1'b1;
        end else if ((grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_ap_ready == 1'b1)) begin
            grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_ap_start_reg <= 1'b1;
        end else if ((grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_ap_ready == 1'b1)) begin
            grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_ap_start_reg <= 1'b1;
        end else if ((grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_ap_ready == 1'b1)) begin
            grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_out_C_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state1_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_matmul_1_Pipeline_loop1_loop2_fu_186_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        in_A_TREADY_int_regslice = grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_in_A_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        in_A_TREADY_int_regslice = grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_in_A_TREADY;
    end else begin
        in_A_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        output_C_address0 = grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_output_C_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        output_C_address0 = grp_matmul_1_Pipeline_loop1_loop2_fu_186_output_C_address0;
    end else begin
        output_C_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        output_C_ce0 = grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_output_C_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        output_C_ce0 = grp_matmul_1_Pipeline_loop1_loop2_fu_186_output_C_ce0;
    end else begin
        output_C_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        output_C_we0 = grp_matmul_1_Pipeline_loop1_loop2_fu_186_output_C_we0;
    end else begin
        output_C_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (grp_matmul_1_Pipeline_loop1_loop2_fu_186_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((regslice_both_out_C_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_matmul_1_Pipeline_loop1_loop2_fu_186_ap_start = grp_matmul_1_Pipeline_loop1_loop2_fu_186_ap_start_reg;

assign grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_ap_start = grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_ap_start_reg;

assign grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_ap_start = grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_ap_start_reg;

assign grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_ap_start = grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_ap_start_reg;

assign grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TREADY = (out_C_TREADY_int_regslice & ap_CS_fsm_state10);

assign in_A_TREADY = regslice_both_in_A_V_data_V_U_ack_in;

assign out_C_TVALID = regslice_both_out_C_V_data_V_U_vld_out;

assign out_C_TVALID_int_regslice = grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TVALID;


reg find_kernel_block = 0;
// synthesis translate_off
`include "matmul_1_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //matmul_1

