// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module activation_quant_generic_round_float_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        x,
        ap_return
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [31:0] x;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [4:0] mask_table_address0;
reg    mask_table_ce0;
wire   [22:0] mask_table_q0;
wire   [4:0] one_half_table_address0;
reg    one_half_table_ce0;
wire   [23:0] one_half_table_q0;
reg   [31:0] x_read_reg_200;
wire    ap_block_pp0_stage0_11001;
wire   [31:0] data_1_fu_72_p1;
reg   [31:0] data_1_reg_205;
wire   [0:0] icmp_ln167_fu_86_p2;
reg   [0:0] icmp_ln167_reg_211;
wire   [0:0] icmp_ln170_fu_92_p2;
reg   [0:0] icmp_ln170_reg_217;
wire   [63:0] zext_ln179_fu_108_p1;
wire    ap_block_pp0_stage0;
wire   [7:0] xs_exp_fu_76_p4;
wire   [4:0] index_fu_98_p4;
wire   [0:0] xs_sign_fu_114_p3;
wire   [31:0] zext_ln175_fu_129_p1;
wire   [31:0] data_fu_133_p2;
wire   [22:0] trunc_ln301_fu_138_p1;
wire   [22:0] xor_ln184_fu_142_p2;
wire   [8:0] tmp_fu_154_p4;
wire   [22:0] xs_sig_fu_148_p2;
wire   [31:0] t_fu_121_p3;
wire   [31:0] t_2_fu_164_p3;
wire   [31:0] select_ln167_fu_172_p3;
wire   [0:0] xor_ln167_fu_183_p2;
wire   [0:0] and_ln170_fu_188_p2;
wire   [31:0] bitcast_ln167_fu_179_p1;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

activation_quant_generic_round_float_s_mask_table_ROM_AUTO_1R #(
    .DataWidth( 23 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
mask_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mask_table_address0),
    .ce0(mask_table_ce0),
    .q0(mask_table_q0)
);

activation_quant_generic_round_float_s_one_half_table_ROM_AUTO_1R #(
    .DataWidth( 24 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
one_half_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(one_half_table_address0),
    .ce0(one_half_table_ce0),
    .q0(one_half_table_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_1_reg_205 <= data_1_fu_72_p1;
        icmp_ln167_reg_211 <= icmp_ln167_fu_86_p2;
        icmp_ln170_reg_217 <= icmp_ln170_fu_92_p2;
        x_read_reg_200 <= x;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mask_table_ce0 = 1'b1;
    end else begin
        mask_table_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        one_half_table_ce0 = 1'b1;
    end else begin
        one_half_table_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign and_ln170_fu_188_p2 = (xor_ln167_fu_183_p2 & icmp_ln170_reg_217);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (1'b0 == ap_ce);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return = ((and_ln170_fu_188_p2[0:0] == 1'b1) ? x_read_reg_200 : bitcast_ln167_fu_179_p1);

assign bitcast_ln167_fu_179_p1 = select_ln167_fu_172_p3;

assign data_1_fu_72_p1 = x;

assign data_fu_133_p2 = (zext_ln175_fu_129_p1 + data_1_reg_205);

assign icmp_ln167_fu_86_p2 = ((xs_exp_fu_76_p4 < 8'd126) ? 1'b1 : 1'b0);

assign icmp_ln170_fu_92_p2 = ((xs_exp_fu_76_p4 > 8'd150) ? 1'b1 : 1'b0);

assign index_fu_98_p4 = {{data_1_fu_72_p1[27:23]}};

assign mask_table_address0 = zext_ln179_fu_108_p1;

assign one_half_table_address0 = zext_ln179_fu_108_p1;

assign select_ln167_fu_172_p3 = ((icmp_ln167_reg_211[0:0] == 1'b1) ? t_fu_121_p3 : t_2_fu_164_p3);

assign t_2_fu_164_p3 = {{tmp_fu_154_p4}, {xs_sig_fu_148_p2}};

assign t_fu_121_p3 = {{xs_sign_fu_114_p3}, {31'd0}};

assign tmp_fu_154_p4 = {{data_fu_133_p2[31:23]}};

assign trunc_ln301_fu_138_p1 = data_fu_133_p2[22:0];

assign xor_ln167_fu_183_p2 = (icmp_ln167_reg_211 ^ 1'd1);

assign xor_ln184_fu_142_p2 = (mask_table_q0 ^ 23'd8388607);

assign xs_exp_fu_76_p4 = {{data_1_fu_72_p1[30:23]}};

assign xs_sig_fu_148_p2 = (xor_ln184_fu_142_p2 & trunc_ln301_fu_138_p1);

assign xs_sign_fu_114_p3 = data_1_reg_205[32'd31];

assign zext_ln175_fu_129_p1 = one_half_table_q0;

assign zext_ln179_fu_108_p1 = index_fu_98_p4;

endmodule //activation_quant_generic_round_float_s
