-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity matmul_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    in_A_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_A_TVALID : IN STD_LOGIC;
    in_A_TREADY : OUT STD_LOGIC;
    in_A_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_A_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_A_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    out_C_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_C_TVALID : OUT STD_LOGIC;
    out_C_TREADY : IN STD_LOGIC;
    out_C_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_C_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_C_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of matmul_1 is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "matmul_1_matmul_1,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu11p-flga2577-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.297000,HLS_SYN_LAT=65,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1935,HLS_SYN_LUT=1768,HLS_VERSION=2023_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (10 downto 0) := "00000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (10 downto 0) := "00000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (10 downto 0) := "00000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (10 downto 0) := "00000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (10 downto 0) := "00000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (10 downto 0) := "00001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (10 downto 0) := "00010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (10 downto 0) := "00100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (10 downto 0) := "01000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";

    signal ap_rst_n_inv : STD_LOGIC;
    signal output_C_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal output_C_ce0 : STD_LOGIC;
    signal output_C_we0 : STD_LOGIC;
    signal output_C_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_ap_start : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_ap_done : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_ap_idle : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_ap_ready : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_in_A_TREADY : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out_ap_vld : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out1_ap_vld : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out2_ap_vld : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out3_ap_vld : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out4 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out4_ap_vld : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out5 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out5_ap_vld : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out6 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out6_ap_vld : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out7 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out7_ap_vld : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out8 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out8_ap_vld : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_ap_start : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_ap_done : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_ap_idle : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_ap_ready : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_in_A_TREADY : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out_ap_vld : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out1_ap_vld : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out2_ap_vld : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out3_ap_vld : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out4 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out4_ap_vld : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out5 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out5_ap_vld : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out6 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out6_ap_vld : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out7 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out7_ap_vld : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out8 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out8_ap_vld : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_phi_out : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_phi_out_ap_vld : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_phi7_out : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_phi7_out_ap_vld : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop1_loop2_fu_186_ap_start : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop1_loop2_fu_186_ap_done : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop1_loop2_fu_186_ap_idle : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop1_loop2_fu_186_ap_ready : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop1_loop2_fu_186_output_C_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_matmul_1_Pipeline_loop1_loop2_fu_186_output_C_ce0 : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop1_loop2_fu_186_output_C_we0 : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop1_loop2_fu_186_output_C_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_ap_start : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_ap_done : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_ap_idle : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_ap_ready : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TREADY : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_output_C_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_output_C_ce0 : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TVALID : STD_LOGIC;
    signal grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_matmul_1_Pipeline_loop1_loop2_fu_186_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal regslice_both_out_C_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal regslice_both_in_A_V_data_V_U_apdone_blk : STD_LOGIC;
    signal in_A_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal in_A_TVALID_int_regslice : STD_LOGIC;
    signal in_A_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in_A_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_A_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal in_A_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_A_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_A_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_A_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal in_A_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_A_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_A_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_A_V_last_V_U_apdone_blk : STD_LOGIC;
    signal in_A_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_A_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_A_V_last_V_U_ack_in : STD_LOGIC;
    signal out_C_TVALID_int_regslice : STD_LOGIC;
    signal out_C_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_out_C_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_C_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_C_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_C_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_C_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_C_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_C_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_C_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_C_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_C_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component matmul_1_matmul_1_Pipeline_loop_input_A1_loop_input_A2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_A_TVALID : IN STD_LOGIC;
        in_A_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        in_A_TREADY : OUT STD_LOGIC;
        in_A_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        in_A_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        in_A_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        p_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out_ap_vld : OUT STD_LOGIC;
        p_out1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out1_ap_vld : OUT STD_LOGIC;
        p_out2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out2_ap_vld : OUT STD_LOGIC;
        p_out3 : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out3_ap_vld : OUT STD_LOGIC;
        p_out4 : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out4_ap_vld : OUT STD_LOGIC;
        p_out5 : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out5_ap_vld : OUT STD_LOGIC;
        p_out6 : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out6_ap_vld : OUT STD_LOGIC;
        p_out7 : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out7_ap_vld : OUT STD_LOGIC;
        p_out8 : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out8_ap_vld : OUT STD_LOGIC );
    end component;


    component matmul_1_matmul_1_Pipeline_loop_input_B1_loop_input_B2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_A_TVALID : IN STD_LOGIC;
        in_A_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        in_A_TREADY : OUT STD_LOGIC;
        in_A_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        in_A_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        in_A_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        p_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out_ap_vld : OUT STD_LOGIC;
        p_out1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out1_ap_vld : OUT STD_LOGIC;
        p_out2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out2_ap_vld : OUT STD_LOGIC;
        p_out3 : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out3_ap_vld : OUT STD_LOGIC;
        p_out4 : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out4_ap_vld : OUT STD_LOGIC;
        p_out5 : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out5_ap_vld : OUT STD_LOGIC;
        p_out6 : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out6_ap_vld : OUT STD_LOGIC;
        p_out7 : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out7_ap_vld : OUT STD_LOGIC;
        p_out8 : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out8_ap_vld : OUT STD_LOGIC;
        p_phi_out : OUT STD_LOGIC_VECTOR (3 downto 0);
        p_phi_out_ap_vld : OUT STD_LOGIC;
        p_phi7_out : OUT STD_LOGIC_VECTOR (3 downto 0);
        p_phi7_out_ap_vld : OUT STD_LOGIC );
    end component;


    component matmul_1_matmul_1_Pipeline_loop1_loop2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_reload99 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_reload98 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_reload97 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_reload96 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_reload95 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_reload94 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_reload93 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_reload92 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        output_C_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        output_C_ce0 : OUT STD_LOGIC;
        output_C_we0 : OUT STD_LOGIC;
        output_C_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_reload118 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_reload117 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_reload116 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_reload115 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_reload114 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_reload113 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_reload112 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_reload111 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_reload110 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component matmul_1_matmul_1_Pipeline_loop_output_C1_loop_output_C2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        out_C_TREADY : IN STD_LOGIC;
        output_C_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        output_C_ce0 : OUT STD_LOGIC;
        output_C_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_phi_reload : IN STD_LOGIC_VECTOR (3 downto 0);
        p_phi7_reload : IN STD_LOGIC_VECTOR (3 downto 0);
        out_C_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_C_TVALID : OUT STD_LOGIC;
        out_C_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_C_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_C_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component matmul_1_output_C_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component matmul_1_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    output_C_U : component matmul_1_output_C_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 9,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => output_C_address0,
        ce0 => output_C_ce0,
        we0 => output_C_we0,
        d0 => grp_matmul_1_Pipeline_loop1_loop2_fu_186_output_C_d0,
        q0 => output_C_q0);

    grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142 : component matmul_1_matmul_1_Pipeline_loop_input_A1_loop_input_A2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_ap_start,
        ap_done => grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_ap_done,
        ap_idle => grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_ap_idle,
        ap_ready => grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_ap_ready,
        in_A_TVALID => in_A_TVALID_int_regslice,
        in_A_TDATA => in_A_TDATA_int_regslice,
        in_A_TREADY => grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_in_A_TREADY,
        in_A_TKEEP => in_A_TKEEP_int_regslice,
        in_A_TSTRB => in_A_TSTRB_int_regslice,
        in_A_TLAST => in_A_TLAST_int_regslice,
        p_out => grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out,
        p_out_ap_vld => grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out_ap_vld,
        p_out1 => grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out1,
        p_out1_ap_vld => grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out1_ap_vld,
        p_out2 => grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out2,
        p_out2_ap_vld => grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out2_ap_vld,
        p_out3 => grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out3,
        p_out3_ap_vld => grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out3_ap_vld,
        p_out4 => grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out4,
        p_out4_ap_vld => grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out4_ap_vld,
        p_out5 => grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out5,
        p_out5_ap_vld => grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out5_ap_vld,
        p_out6 => grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out6,
        p_out6_ap_vld => grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out6_ap_vld,
        p_out7 => grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out7,
        p_out7_ap_vld => grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out7_ap_vld,
        p_out8 => grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out8,
        p_out8_ap_vld => grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out8_ap_vld);

    grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163 : component matmul_1_matmul_1_Pipeline_loop_input_B1_loop_input_B2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_ap_start,
        ap_done => grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_ap_done,
        ap_idle => grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_ap_idle,
        ap_ready => grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_ap_ready,
        in_A_TVALID => in_A_TVALID_int_regslice,
        in_A_TDATA => in_A_TDATA_int_regslice,
        in_A_TREADY => grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_in_A_TREADY,
        in_A_TKEEP => in_A_TKEEP_int_regslice,
        in_A_TSTRB => in_A_TSTRB_int_regslice,
        in_A_TLAST => in_A_TLAST_int_regslice,
        p_out => grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out,
        p_out_ap_vld => grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out_ap_vld,
        p_out1 => grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out1,
        p_out1_ap_vld => grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out1_ap_vld,
        p_out2 => grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out2,
        p_out2_ap_vld => grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out2_ap_vld,
        p_out3 => grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out3,
        p_out3_ap_vld => grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out3_ap_vld,
        p_out4 => grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out4,
        p_out4_ap_vld => grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out4_ap_vld,
        p_out5 => grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out5,
        p_out5_ap_vld => grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out5_ap_vld,
        p_out6 => grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out6,
        p_out6_ap_vld => grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out6_ap_vld,
        p_out7 => grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out7,
        p_out7_ap_vld => grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out7_ap_vld,
        p_out8 => grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out8,
        p_out8_ap_vld => grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out8_ap_vld,
        p_phi_out => grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_phi_out,
        p_phi_out_ap_vld => grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_phi_out_ap_vld,
        p_phi7_out => grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_phi7_out,
        p_phi7_out_ap_vld => grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_phi7_out_ap_vld);

    grp_matmul_1_Pipeline_loop1_loop2_fu_186 : component matmul_1_matmul_1_Pipeline_loop1_loop2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_matmul_1_Pipeline_loop1_loop2_fu_186_ap_start,
        ap_done => grp_matmul_1_Pipeline_loop1_loop2_fu_186_ap_done,
        ap_idle => grp_matmul_1_Pipeline_loop1_loop2_fu_186_ap_idle,
        ap_ready => grp_matmul_1_Pipeline_loop1_loop2_fu_186_ap_ready,
        p_reload99 => grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out8,
        p_reload98 => grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out7,
        p_reload97 => grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out6,
        p_reload96 => grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out5,
        p_reload95 => grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out4,
        p_reload94 => grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out3,
        p_reload93 => grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out2,
        p_reload92 => grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out1,
        p_reload => grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_p_out,
        output_C_address0 => grp_matmul_1_Pipeline_loop1_loop2_fu_186_output_C_address0,
        output_C_ce0 => grp_matmul_1_Pipeline_loop1_loop2_fu_186_output_C_ce0,
        output_C_we0 => grp_matmul_1_Pipeline_loop1_loop2_fu_186_output_C_we0,
        output_C_d0 => grp_matmul_1_Pipeline_loop1_loop2_fu_186_output_C_d0,
        p_reload118 => grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out8,
        p_reload117 => grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out7,
        p_reload116 => grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out6,
        p_reload115 => grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out5,
        p_reload114 => grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out4,
        p_reload113 => grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out3,
        p_reload112 => grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out2,
        p_reload111 => grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out1,
        p_reload110 => grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_out);

    grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209 : component matmul_1_matmul_1_Pipeline_loop_output_C1_loop_output_C2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_ap_start,
        ap_done => grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_ap_done,
        ap_idle => grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_ap_idle,
        ap_ready => grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_ap_ready,
        out_C_TREADY => grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TREADY,
        output_C_address0 => grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_output_C_address0,
        output_C_ce0 => grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_output_C_ce0,
        output_C_q0 => output_C_q0,
        p_phi_reload => grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_phi_out,
        p_phi7_reload => grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_p_phi7_out,
        out_C_TDATA => grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TDATA,
        out_C_TVALID => grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TVALID,
        out_C_TKEEP => grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TKEEP,
        out_C_TSTRB => grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TSTRB,
        out_C_TLAST => grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TLAST);

    regslice_both_in_A_V_data_V_U : component matmul_1_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_A_TDATA,
        vld_in => in_A_TVALID,
        ack_in => regslice_both_in_A_V_data_V_U_ack_in,
        data_out => in_A_TDATA_int_regslice,
        vld_out => in_A_TVALID_int_regslice,
        ack_out => in_A_TREADY_int_regslice,
        apdone_blk => regslice_both_in_A_V_data_V_U_apdone_blk);

    regslice_both_in_A_V_keep_V_U : component matmul_1_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_A_TKEEP,
        vld_in => in_A_TVALID,
        ack_in => regslice_both_in_A_V_keep_V_U_ack_in,
        data_out => in_A_TKEEP_int_regslice,
        vld_out => regslice_both_in_A_V_keep_V_U_vld_out,
        ack_out => in_A_TREADY_int_regslice,
        apdone_blk => regslice_both_in_A_V_keep_V_U_apdone_blk);

    regslice_both_in_A_V_strb_V_U : component matmul_1_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_A_TSTRB,
        vld_in => in_A_TVALID,
        ack_in => regslice_both_in_A_V_strb_V_U_ack_in,
        data_out => in_A_TSTRB_int_regslice,
        vld_out => regslice_both_in_A_V_strb_V_U_vld_out,
        ack_out => in_A_TREADY_int_regslice,
        apdone_blk => regslice_both_in_A_V_strb_V_U_apdone_blk);

    regslice_both_in_A_V_last_V_U : component matmul_1_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_A_TLAST,
        vld_in => in_A_TVALID,
        ack_in => regslice_both_in_A_V_last_V_U_ack_in,
        data_out => in_A_TLAST_int_regslice,
        vld_out => regslice_both_in_A_V_last_V_U_vld_out,
        ack_out => in_A_TREADY_int_regslice,
        apdone_blk => regslice_both_in_A_V_last_V_U_apdone_blk);

    regslice_both_out_C_V_data_V_U : component matmul_1_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TDATA,
        vld_in => grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TVALID,
        ack_in => out_C_TREADY_int_regslice,
        data_out => out_C_TDATA,
        vld_out => regslice_both_out_C_V_data_V_U_vld_out,
        ack_out => out_C_TREADY,
        apdone_blk => regslice_both_out_C_V_data_V_U_apdone_blk);

    regslice_both_out_C_V_keep_V_U : component matmul_1_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TKEEP,
        vld_in => grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TVALID,
        ack_in => regslice_both_out_C_V_keep_V_U_ack_in_dummy,
        data_out => out_C_TKEEP,
        vld_out => regslice_both_out_C_V_keep_V_U_vld_out,
        ack_out => out_C_TREADY,
        apdone_blk => regslice_both_out_C_V_keep_V_U_apdone_blk);

    regslice_both_out_C_V_strb_V_U : component matmul_1_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TSTRB,
        vld_in => grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TVALID,
        ack_in => regslice_both_out_C_V_strb_V_U_ack_in_dummy,
        data_out => out_C_TSTRB,
        vld_out => regslice_both_out_C_V_strb_V_U_vld_out,
        ack_out => out_C_TREADY,
        apdone_blk => regslice_both_out_C_V_strb_V_U_apdone_blk);

    regslice_both_out_C_V_last_V_U : component matmul_1_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TLAST,
        vld_in => grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TVALID,
        ack_in => regslice_both_out_C_V_last_V_U_ack_in_dummy,
        data_out => out_C_TLAST,
        vld_out => regslice_both_out_C_V_last_V_U_vld_out,
        ack_out => out_C_TREADY,
        apdone_blk => regslice_both_out_C_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_matmul_1_Pipeline_loop1_loop2_fu_186_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_matmul_1_Pipeline_loop1_loop2_fu_186_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                    grp_matmul_1_Pipeline_loop1_loop2_fu_186_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_matmul_1_Pipeline_loop1_loop2_fu_186_ap_ready = ap_const_logic_1)) then 
                    grp_matmul_1_Pipeline_loop1_loop2_fu_186_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_ap_ready = ap_const_logic_1)) then 
                    grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_ap_ready = ap_const_logic_1)) then 
                    grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                    grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_ap_ready = ap_const_logic_1)) then 
                    grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_ap_done, grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_ap_done, grp_matmul_1_Pipeline_loop1_loop2_fu_186_ap_done, grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_ap_done, ap_CS_fsm, ap_CS_fsm_state3, ap_CS_fsm_state6, ap_CS_fsm_state8, ap_CS_fsm_state10, regslice_both_out_C_V_data_V_U_apdone_blk, ap_CS_fsm_state11)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state8) and (grp_matmul_1_Pipeline_loop1_loop2_fu_186_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state10) and (grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when ap_ST_fsm_state11 => 
                if (((regslice_both_out_C_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state11))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state10_blk_assign_proc : process(grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_ap_done)
    begin
        if ((grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state10_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state10_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state11_blk_assign_proc : process(regslice_both_out_C_V_data_V_U_apdone_blk)
    begin
        if ((regslice_both_out_C_V_data_V_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state11_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state11_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state1_blk <= ap_const_logic_0;
    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_ap_done)
    begin
        if ((grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_ap_done)
    begin
        if ((grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_ST_fsm_state8_blk_assign_proc : process(grp_matmul_1_Pipeline_loop1_loop2_fu_186_ap_done)
    begin
        if ((grp_matmul_1_Pipeline_loop1_loop2_fu_186_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    grp_matmul_1_Pipeline_loop1_loop2_fu_186_ap_start <= grp_matmul_1_Pipeline_loop1_loop2_fu_186_ap_start_reg;
    grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_ap_start <= grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_ap_start_reg;
    grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_ap_start <= grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_ap_start_reg;
    grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_ap_start <= grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_ap_start_reg;
    grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TREADY <= (out_C_TREADY_int_regslice and ap_CS_fsm_state10);
    in_A_TREADY <= regslice_both_in_A_V_data_V_U_ack_in;

    in_A_TREADY_int_regslice_assign_proc : process(grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_in_A_TREADY, grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_in_A_TREADY, ap_CS_fsm_state3, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            in_A_TREADY_int_regslice <= grp_matmul_1_Pipeline_loop_input_B1_loop_input_B2_fu_163_in_A_TREADY;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_A_TREADY_int_regslice <= grp_matmul_1_Pipeline_loop_input_A1_loop_input_A2_fu_142_in_A_TREADY;
        else 
            in_A_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    out_C_TVALID <= regslice_both_out_C_V_data_V_U_vld_out;
    out_C_TVALID_int_regslice <= grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_out_C_TVALID;

    output_C_address0_assign_proc : process(grp_matmul_1_Pipeline_loop1_loop2_fu_186_output_C_address0, grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_output_C_address0, ap_CS_fsm_state8, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            output_C_address0 <= grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_output_C_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            output_C_address0 <= grp_matmul_1_Pipeline_loop1_loop2_fu_186_output_C_address0;
        else 
            output_C_address0 <= "XXXX";
        end if; 
    end process;


    output_C_ce0_assign_proc : process(grp_matmul_1_Pipeline_loop1_loop2_fu_186_output_C_ce0, grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_output_C_ce0, ap_CS_fsm_state8, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            output_C_ce0 <= grp_matmul_1_Pipeline_loop_output_C1_loop_output_C2_fu_209_output_C_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            output_C_ce0 <= grp_matmul_1_Pipeline_loop1_loop2_fu_186_output_C_ce0;
        else 
            output_C_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    output_C_we0_assign_proc : process(grp_matmul_1_Pipeline_loop1_loop2_fu_186_output_C_we0, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            output_C_we0 <= grp_matmul_1_Pipeline_loop1_loop2_fu_186_output_C_we0;
        else 
            output_C_we0 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
