// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module matmul_1_matmul_1_Pipeline_loop_input_B1_loop_input_B2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_A_TVALID,
        in_A_TDATA,
        in_A_TREADY,
        in_A_TKEEP,
        in_A_TSTRB,
        in_A_TLAST,
        p_out,
        p_out_ap_vld,
        p_out1,
        p_out1_ap_vld,
        p_out2,
        p_out2_ap_vld,
        p_out3,
        p_out3_ap_vld,
        p_out4,
        p_out4_ap_vld,
        p_out5,
        p_out5_ap_vld,
        p_out6,
        p_out6_ap_vld,
        p_out7,
        p_out7_ap_vld,
        p_out8,
        p_out8_ap_vld,
        p_phi_out,
        p_phi_out_ap_vld,
        p_phi7_out,
        p_phi7_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in_A_TVALID;
input  [31:0] in_A_TDATA;
output   in_A_TREADY;
input  [3:0] in_A_TKEEP;
input  [3:0] in_A_TSTRB;
input  [0:0] in_A_TLAST;
output  [31:0] p_out;
output   p_out_ap_vld;
output  [31:0] p_out1;
output   p_out1_ap_vld;
output  [31:0] p_out2;
output   p_out2_ap_vld;
output  [31:0] p_out3;
output   p_out3_ap_vld;
output  [31:0] p_out4;
output   p_out4_ap_vld;
output  [31:0] p_out5;
output   p_out5_ap_vld;
output  [31:0] p_out6;
output   p_out6_ap_vld;
output  [31:0] p_out7;
output   p_out7_ap_vld;
output  [31:0] p_out8;
output   p_out8_ap_vld;
output  [3:0] p_phi_out;
output   p_phi_out_ap_vld;
output  [3:0] p_phi7_out;
output   p_phi7_out_ap_vld;

reg ap_idle;
reg in_A_TREADY;
reg p_out_ap_vld;
reg p_out1_ap_vld;
reg p_out2_ap_vld;
reg p_out3_ap_vld;
reg p_out4_ap_vld;
reg p_out5_ap_vld;
reg p_out6_ap_vld;
reg p_out7_ap_vld;
reg p_out8_ap_vld;
reg p_phi_out_ap_vld;
reg p_phi7_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln36_fu_241_p2;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in_A_TDATA_blk_n;
reg   [3:0] p_phi7_fu_78;
reg   [3:0] p_phi_fu_82;
reg   [1:0] col_fu_86;
wire   [1:0] add_ln38_fu_348_p2;
wire    ap_loop_init;
reg   [1:0] ap_sig_allocacmp_col_load;
reg   [1:0] row_fu_90;
wire   [1:0] select_ln36_fu_279_p3;
reg   [1:0] ap_sig_allocacmp_row_load;
reg   [3:0] indvar_flatten41_fu_94;
wire   [3:0] add_ln36_1_fu_247_p2;
reg   [3:0] ap_sig_allocacmp_indvar_flatten41_load;
reg   [31:0] empty_fu_98;
wire   [31:0] input_B_0_fu_299_p1;
wire   [1:0] select_ln14_fu_271_p3;
reg   [31:0] empty_9_fu_102;
reg   [31:0] empty_10_fu_106;
reg   [31:0] empty_11_fu_110;
reg   [31:0] empty_12_fu_114;
reg   [31:0] empty_13_fu_118;
reg   [31:0] empty_14_fu_122;
reg   [31:0] empty_15_fu_126;
reg   [31:0] empty_16_fu_130;
wire   [0:0] icmp_ln38_fu_265_p2;
wire   [1:0] add_ln36_fu_259_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 p_phi7_fu_78 = 4'd0;
#0 p_phi_fu_82 = 4'd0;
#0 col_fu_86 = 2'd0;
#0 row_fu_90 = 2'd0;
#0 indvar_flatten41_fu_94 = 4'd0;
#0 empty_fu_98 = 32'd0;
#0 empty_9_fu_102 = 32'd0;
#0 empty_10_fu_106 = 32'd0;
#0 empty_11_fu_110 = 32'd0;
#0 empty_12_fu_114 = 32'd0;
#0 empty_13_fu_118 = 32'd0;
#0 empty_14_fu_122 = 32'd0;
#0 empty_15_fu_126 = 32'd0;
#0 empty_16_fu_130 = 32'd0;
#0 ap_done_reg = 1'b0;
end

matmul_1_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln36_fu_241_p2 == 1'd0)) begin
            col_fu_86 <= add_ln38_fu_348_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            col_fu_86 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln36_fu_241_p2 == 1'd0)) begin
            indvar_flatten41_fu_94 <= add_ln36_1_fu_247_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten41_fu_94 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln36_fu_241_p2 == 1'd0)) begin
            row_fu_90 <= select_ln36_fu_279_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            row_fu_90 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~(select_ln14_fu_271_p3 == 2'd1) & ~(select_ln14_fu_271_p3 == 2'd0) & (select_ln36_fu_279_p3 == 2'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln36_fu_241_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        empty_10_fu_106 <= input_B_0_fu_299_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((select_ln36_fu_279_p3 == 2'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln36_fu_241_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (select_ln14_fu_271_p3 == 2'd0))) begin
        empty_11_fu_110 <= input_B_0_fu_299_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((select_ln36_fu_279_p3 == 2'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln36_fu_241_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (select_ln14_fu_271_p3 == 2'd1))) begin
        empty_12_fu_114 <= input_B_0_fu_299_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~(select_ln14_fu_271_p3 == 2'd1) & ~(select_ln14_fu_271_p3 == 2'd0) & (select_ln36_fu_279_p3 == 2'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln36_fu_241_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        empty_13_fu_118 <= input_B_0_fu_299_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~(select_ln36_fu_279_p3 == 2'd1) & ~(select_ln36_fu_279_p3 == 2'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln36_fu_241_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (select_ln14_fu_271_p3 == 2'd0))) begin
        empty_14_fu_122 <= input_B_0_fu_299_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~(select_ln36_fu_279_p3 == 2'd1) & ~(select_ln36_fu_279_p3 == 2'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln36_fu_241_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (select_ln14_fu_271_p3 == 2'd1))) begin
        empty_15_fu_126 <= input_B_0_fu_299_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~(select_ln36_fu_279_p3 == 2'd1) & ~(select_ln14_fu_271_p3 == 2'd1) & ~(select_ln14_fu_271_p3 == 2'd0) & ~(select_ln36_fu_279_p3 == 2'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln36_fu_241_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        empty_16_fu_130 <= input_B_0_fu_299_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((select_ln36_fu_279_p3 == 2'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln36_fu_241_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (select_ln14_fu_271_p3 == 2'd1))) begin
        empty_9_fu_102 <= input_B_0_fu_299_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((select_ln36_fu_279_p3 == 2'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln36_fu_241_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (select_ln14_fu_271_p3 == 2'd0))) begin
        empty_fu_98 <= input_B_0_fu_299_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln36_fu_241_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_phi7_fu_78 <= in_A_TSTRB;
        p_phi_fu_82 <= in_A_TKEEP;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln36_fu_241_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_col_load = 2'd0;
    end else begin
        ap_sig_allocacmp_col_load = col_fu_86;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_indvar_flatten41_load = 4'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten41_load = indvar_flatten41_fu_94;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_row_load = 2'd0;
    end else begin
        ap_sig_allocacmp_row_load = row_fu_90;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln36_fu_241_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        in_A_TDATA_blk_n = in_A_TVALID;
    end else begin
        in_A_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln36_fu_241_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        in_A_TREADY = 1'b1;
    end else begin
        in_A_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln36_fu_241_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_out1_ap_vld = 1'b1;
    end else begin
        p_out1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln36_fu_241_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_out2_ap_vld = 1'b1;
    end else begin
        p_out2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln36_fu_241_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_out3_ap_vld = 1'b1;
    end else begin
        p_out3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln36_fu_241_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_out4_ap_vld = 1'b1;
    end else begin
        p_out4_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln36_fu_241_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_out5_ap_vld = 1'b1;
    end else begin
        p_out5_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln36_fu_241_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_out6_ap_vld = 1'b1;
    end else begin
        p_out6_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln36_fu_241_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_out7_ap_vld = 1'b1;
    end else begin
        p_out7_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln36_fu_241_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_out8_ap_vld = 1'b1;
    end else begin
        p_out8_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln36_fu_241_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_out_ap_vld = 1'b1;
    end else begin
        p_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln36_fu_241_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_phi7_out_ap_vld = 1'b1;
    end else begin
        p_phi7_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln36_fu_241_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_phi_out_ap_vld = 1'b1;
    end else begin
        p_phi_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln36_1_fu_247_p2 = (ap_sig_allocacmp_indvar_flatten41_load + 4'd1);

assign add_ln36_fu_259_p2 = (ap_sig_allocacmp_row_load + 2'd1);

assign add_ln38_fu_348_p2 = (select_ln14_fu_271_p3 + 2'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((icmp_ln36_fu_241_p2 == 1'd0) & (in_A_TVALID == 1'b0)));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln36_fu_241_p2 = ((ap_sig_allocacmp_indvar_flatten41_load == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln38_fu_265_p2 = ((ap_sig_allocacmp_col_load == 2'd3) ? 1'b1 : 1'b0);

assign input_B_0_fu_299_p1 = in_A_TDATA;

assign p_out = empty_16_fu_130;

assign p_out1 = empty_15_fu_126;

assign p_out2 = empty_14_fu_122;

assign p_out3 = empty_13_fu_118;

assign p_out4 = empty_12_fu_114;

assign p_out5 = empty_11_fu_110;

assign p_out6 = empty_10_fu_106;

assign p_out7 = empty_9_fu_102;

assign p_out8 = empty_fu_98;

assign p_phi7_out = p_phi7_fu_78;

assign p_phi_out = p_phi_fu_82;

assign select_ln14_fu_271_p3 = ((icmp_ln38_fu_265_p2[0:0] == 1'b1) ? 2'd0 : ap_sig_allocacmp_col_load);

assign select_ln36_fu_279_p3 = ((icmp_ln38_fu_265_p2[0:0] == 1'b1) ? add_ln36_fu_259_p2 : ap_sig_allocacmp_row_load);

endmodule //matmul_1_matmul_1_Pipeline_loop_input_B1_loop_input_B2
