-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity MatMul is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    A_0_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    A_0_ce0 : OUT STD_LOGIC;
    A_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    A_1_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    A_1_ce0 : OUT STD_LOGIC;
    A_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    B_0_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    B_0_ce0 : OUT STD_LOGIC;
    B_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    B_0_address1 : OUT STD_LOGIC_VECTOR (0 downto 0);
    B_0_ce1 : OUT STD_LOGIC;
    B_0_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    B_1_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    B_1_ce0 : OUT STD_LOGIC;
    B_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    B_1_address1 : OUT STD_LOGIC_VECTOR (0 downto 0);
    B_1_ce1 : OUT STD_LOGIC;
    B_1_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    y_0_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    y_0_ce0 : OUT STD_LOGIC;
    y_0_we0 : OUT STD_LOGIC;
    y_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    y_1_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    y_1_ce0 : OUT STD_LOGIC;
    y_1_we0 : OUT STD_LOGIC;
    y_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of MatMul is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "MatMul_MatMul,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu11p-flga2577-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.502000,HLS_SYN_LAT=6,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=139,HLS_SYN_LUT=235,HLS_VERSION=2023_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal B_0_load_reg_128 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal B_1_load_reg_133 : STD_LOGIC_VECTOR (31 downto 0);
    signal B_0_load_1_reg_138 : STD_LOGIC_VECTOR (31 downto 0);
    signal B_1_load_1_reg_143 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_ap_start : STD_LOGIC;
    signal grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_ap_done : STD_LOGIC;
    signal grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_ap_idle : STD_LOGIC;
    signal grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_ap_ready : STD_LOGIC;
    signal grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_y_1_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_y_1_ce0 : STD_LOGIC;
    signal grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_y_1_we0 : STD_LOGIC;
    signal grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_y_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_y_0_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_y_0_ce0 : STD_LOGIC;
    signal grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_y_0_we0 : STD_LOGIC;
    signal grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_y_0_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_A_0_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_A_0_ce0 : STD_LOGIC;
    signal grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_A_1_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_A_1_ce0 : STD_LOGIC;
    signal grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component MatMul_MatMul_Pipeline_VITIS_LOOP_10_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        y_1_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        y_1_ce0 : OUT STD_LOGIC;
        y_1_we0 : OUT STD_LOGIC;
        y_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        y_0_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        y_0_ce0 : OUT STD_LOGIC;
        y_0_we0 : OUT STD_LOGIC;
        y_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        A_0_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        A_0_ce0 : OUT STD_LOGIC;
        A_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        A_1_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        A_1_ce0 : OUT STD_LOGIC;
        A_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        B_0_load : IN STD_LOGIC_VECTOR (31 downto 0);
        B_0_load_1 : IN STD_LOGIC_VECTOR (31 downto 0);
        B_1_load : IN STD_LOGIC_VECTOR (31 downto 0);
        B_1_load_1 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88 : component MatMul_MatMul_Pipeline_VITIS_LOOP_10_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_ap_start,
        ap_done => grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_ap_done,
        ap_idle => grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_ap_idle,
        ap_ready => grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_ap_ready,
        y_1_address0 => grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_y_1_address0,
        y_1_ce0 => grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_y_1_ce0,
        y_1_we0 => grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_y_1_we0,
        y_1_d0 => grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_y_1_d0,
        y_0_address0 => grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_y_0_address0,
        y_0_ce0 => grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_y_0_ce0,
        y_0_we0 => grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_y_0_we0,
        y_0_d0 => grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_y_0_d0,
        A_0_address0 => grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_A_0_address0,
        A_0_ce0 => grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_A_0_ce0,
        A_0_q0 => A_0_q0,
        A_1_address0 => grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_A_1_address0,
        A_1_ce0 => grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_A_1_ce0,
        A_1_q0 => A_1_q0,
        B_0_load => B_0_load_reg_128,
        B_0_load_1 => B_0_load_1_reg_138,
        B_1_load => B_1_load_reg_133,
        B_1_load_1 => B_1_load_1_reg_143);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_ap_ready = ap_const_logic_1)) then 
                    grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                B_0_load_1_reg_138 <= B_0_q0;
                B_0_load_reg_128 <= B_0_q1;
                B_1_load_1_reg_143 <= B_1_q0;
                B_1_load_reg_133 <= B_1_q1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_ap_done, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    A_0_address0 <= grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_A_0_address0;
    A_0_ce0 <= grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_A_0_ce0;
    A_1_address0 <= grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_A_1_address0;
    A_1_ce0 <= grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_A_1_ce0;
    B_0_address0 <= ap_const_lv64_1(1 - 1 downto 0);
    B_0_address1 <= ap_const_lv64_0(1 - 1 downto 0);

    B_0_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            B_0_ce0 <= ap_const_logic_1;
        else 
            B_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    B_0_ce1_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            B_0_ce1 <= ap_const_logic_1;
        else 
            B_0_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    B_1_address0 <= ap_const_lv64_1(1 - 1 downto 0);
    B_1_address1 <= ap_const_lv64_0(1 - 1 downto 0);

    B_1_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            B_1_ce0 <= ap_const_logic_1;
        else 
            B_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    B_1_ce1_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            B_1_ce1 <= ap_const_logic_1;
        else 
            B_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_ap_done)
    begin
        if ((grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_ap_done, ap_CS_fsm_state3)
    begin
        if (((grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_ap_done, ap_CS_fsm_state3)
    begin
        if (((grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_ap_start <= grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_ap_start_reg;
    y_0_address0 <= grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_y_0_address0;
    y_0_ce0 <= grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_y_0_ce0;
    y_0_d0 <= grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_y_0_d0;
    y_0_we0 <= grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_y_0_we0;
    y_1_address0 <= grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_y_1_address0;
    y_1_ce0 <= grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_y_1_ce0;
    y_1_d0 <= grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_y_1_d0;
    y_1_we0 <= grp_MatMul_Pipeline_VITIS_LOOP_10_1_fu_88_y_1_we0;
end behav;
